server:
  port: 8080
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Tokyo
    username: just
    password: abcd1234
    
  jpa:
    open-in-view: true
    hibernate:
    #첫실행만 create, 두번째부터 update로 수정해야 한다. 아니면 매번 새로 만들어서 기존데이터 삭제됨.
    #create, update, none 세가지 항몽이 있다.
      ddl-auto: create
      #네이밍 항목에서
      naming:
        #PhysicalNamingStrategyStandardImpl은 Entity필드명 그대로 테이블에 칼럼 만들어 주고
        #org.spingframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy은 언더바를 넣어준다.
        #예를들어 필드명을 myEmail으로 했다면 my_email로 칼럼이 생성된다.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
      #use-new-id-generator-mappings: false  //jpa가 사용하는 기본 넘버링 전략을 따라감.true
      #mysql의 넘버링 전략을 사용하기 위해 false로 하고 User클래스의 
      #@GeneratedValue(strategy = GenerationType.IDENTITY)를 통해 db의 전략을 따라가는걸로 설정.
      # 참고로 에러가 떠서 여기에서는 그냥 이 항목을 지웠다.
    show-sql: true   #콘솔에 sql문 출력해줌.
    properties:
      hibernate.format_sql: true #원래는 sql문 한줄로 출력하는데 얘를 넣으면 정렬해서 보여줌.

  jackson:
    serialization:
      fail-on-empty-beans: false